from __future__ import annotations

import argparse
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

from src.apps.run_minimal_chat import SurfaceNormalizer
from src.core.io.lsd_lexicon import load_lexicon_container
from src.core.schema import DialogueState, LexiconContainer, new_session_id
from src.training.action_bandit import ActionBanditConfig, ActionBanditStore
from src.training.external_evaluator import HeuristicExternalEvaluatorConfig, LLMExternalEvaluatorConfig, build_external_evaluator
from src.training.learning_central import LearningRuntimeConfig, run_learning_episode
from src.training.llm_gateway import LLMGateway
from src.training.policy_memory import PolicyMemoryConfig, PolicyMemoryStore
from src.training.reward_aggregator import RewardAggregator, RewardAggregatorConfig
from src.training.target_generator import LLMTargetGeneratorConfig, build_target_generator
from src.training.teacher_guidance import TeacherGuidanceConfig, TeacherGuidedReranker
from src.utils.logging import setup_logging
from src.utils.settings import apply_arg_defaults, build_dataclass_config, get_setting, load_settings

LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class AutoGeneratedInput:
    text: str
    source: str
    model: str = ''
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass(slots=True)
class LLMInputGeneratorConfig:
    temperature: float = 0.9
    max_output_tokens: int = 120
    history_inputs_limit: int = 8
    history_targets_limit: int = 4
    diversity_cycle: tuple[str, ...] = (
        '質問',
        '説明要求',
        '確認',
        '共感・相談',
        '予定確認',
        '雑談',
    )


class LLMInputGenerator:
    def __init__(
        self,
        gateway: LLMGateway | None = None,
        config: LLMInputGeneratorConfig | None = None,
    ) -> None:
        self.gateway = gateway or LLMGateway()
        self.config = config or LLMInputGeneratorConfig()

    def generate(
        self,
        *,
        loop_index: int,
        history_inputs: Sequence[str],
        history_targets: Sequence[str],
        seed_topic: str = '',
    ) -> AutoGeneratedInput:
        input_limit = max(1, int(self.config.history_inputs_limit))
        target_limit = max(1, int(self.config.history_targets_limit))
        recent_inputs = '\n'.join(f'- {text}' for text in history_inputs[-input_limit:]) or '- (none)'
        recent_targets = '\n'.join(f'- {text}' for text in history_targets[-target_limit:]) or '- (none)'
        topic_line = seed_topic.strip() or '日常会話全般'
        diversity_cycle = tuple(self.config.diversity_cycle or ()) or ('質問', '説明要求', '確認', '共感・相談', '予定確認', '雑談')
        target_style = diversity_cycle[(max(0, int(loop_index)) - 1) % len(diversity_cycle)]

        system_prompt = (
            'あなたは日本語対話学習データの入力生成器です。'
            '学習用のユーザー発話を1件だけ自然な日本語で作成してください。'
            '説明や見出しは不要で、発話本文だけを返してください。'
        )
        user_prompt = (
            f'現在の学習ループ番号: {loop_index}\n'
            f'重点トピック: {topic_line}\n'
            f'今回必ず含めたい発話タイプ: {target_style}\n\n'
            '最近の入力例:\n'
            f'{recent_inputs}\n\n'
            '最近の教師応答例:\n'
            f'{recent_targets}\n\n'
            '条件:\n'
            '- 日本語の自然な1〜2文\n'
            f'- 今回は特に「{target_style}」に寄せる\n'
            '- 日常会話・質問・確認・軽い相談をバランスよく混ぜる\n'
            '- 主語省略・照応・複文を適度に混ぜて入力分布を広げる\n'
            '- 同じ話題や表現の繰り返しを避ける\n'
            '- 短すぎる単語列ではなく、実際のユーザー入力らしくする\n'
            '- 暴力・違法・露骨な性的内容・個人情報は避ける\n'
            '- 発話本文だけを返す\n'
        )
        response = self.gateway.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            purpose='input_generation',
            temperature=float(self.config.temperature),
            max_output_tokens=max(1, int(self.config.max_output_tokens)),
        )
        text = self._clean_text(response.text)
        if not text:
            raise RuntimeError('Input generator returned empty text.')
        LOGGER.info('input_generator.llm.done model=%s text=%s', response.model, text)
        return AutoGeneratedInput(
            text=text,
            source=response.provider,
            model=response.model,
            metadata={'loop_index': loop_index, 'seed_topic': topic_line},
        )

    def _clean_text(self, text: str) -> str:
        cleaned = str(text or '').strip().strip('"\'“”')
        lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
        if not lines:
            return ''
        merged = ' '.join(lines)
        return merged.replace('ユーザー:', '').replace('入力:', '').strip()


class EchoInputGenerator:
    def __init__(self, fallback_text: str) -> None:
        self.fallback_text = str(fallback_text or '').strip() or 'こんにちは。今日はどんな一日になりそうですか。'

    def generate(
        self,
        *,
        loop_index: int,
        history_inputs: Sequence[str],
        history_targets: Sequence[str],
        seed_topic: str = '',
    ) -> AutoGeneratedInput:
        return AutoGeneratedInput(
            text=self.fallback_text,
            source='echo',
            metadata={'loop_index': loop_index, 'seed_topic': seed_topic},
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description='LSLM v3 auto loop learning runner')
    parser.add_argument('--lexicon', default=None)
    parser.add_argument('--trace-dir', default=None)
    parser.add_argument('--dataset-dir', default=None)
    parser.add_argument('--policy-memory', default=None)
    parser.add_argument('--action-bandit', default=None)
    parser.add_argument('--no-policy-memory', action='store_true')
    parser.add_argument('--no-action-bandit', action='store_true')
    parser.add_argument('--no-trace', action='store_true')
    parser.add_argument('--no-dataset', action='store_true')
    parser.add_argument('--debug', action='store_true')
    parser.add_argument('--episodes', type=int, default=None)
    parser.add_argument('--target-mode', choices=['llm', 'echo'], default=None)
    parser.add_argument('--external-mode', choices=['llm', 'heuristic', 'none'], default=None)
    parser.add_argument('--input-mode', choices=['llm', 'echo'], default=None)
    parser.add_argument('--alpha', type=float, default=None)
    parser.add_argument('--beta', type=float, default=None)
    parser.add_argument('--teacher-target-weight', type=float, default=None)
    parser.add_argument('--external-fallback', choices=['neutral', 'internal'], default=None)
    parser.add_argument('--neutral-external-score', type=float, default=None)
    parser.add_argument('--seed-topic', default=None)
    parser.add_argument('--seed-text', default=None)
    parser.add_argument('--report-every', type=int, default=None)
    parser.add_argument('--log-dir', default='logs')
    parser.add_argument('--loop-index-offset', type=int, default=0)
    return parser


def resolve_args(args: argparse.Namespace) -> argparse.Namespace:
    settings = load_settings()
    return apply_arg_defaults(
        args,
        settings,
        [
            ('lexicon', ('paths', 'lexicon'), 'libs/dict.lsdx'),
            ('trace_dir', ('paths', 'trace_dir'), 'runtime/traces'),
            ('dataset_dir', ('paths', 'dataset_dir'), 'runtime/datasets'),
            ('policy_memory', ('paths', 'policy_memory'), 'runtime/policy_memory.json'),
            ('action_bandit', ('paths', 'action_bandit'), 'runtime/action_bandit.json'),
            ('episodes', ('learning', 'episodes'), 1),
            ('target_mode', ('learning', 'target_mode'), 'llm'),
            ('external_mode', ('learning', 'external_mode'), 'llm'),
            ('input_mode', ('learning', 'input_mode'), 'llm'),
            ('alpha', ('learning', 'reward_aggregator', 'alpha'), 0.8),
            ('beta', ('learning', 'reward_aggregator', 'beta'), 0.2),
            ('teacher_target_weight', ('learning', 'teacher_target_weight'), 0.35),
            ('external_fallback', ('learning', 'reward_aggregator', 'fallback_strategy'), 'neutral'),
            ('neutral_external_score', ('learning', 'reward_aggregator', 'neutral_external_score'), 0.5),
            ('seed_topic', ('learning', 'seed_topic'), ''),
            ('seed_text', ('learning', 'seed_text'), 'こんにちは。今日はどんな一日になりそうですか。'),
            ('report_every', ('learning', 'report_every'), 1),
        ],
    )


def load_lexicon(path: Path) -> LexiconContainer:
    LOGGER.info('lexicon.load.start path=%s', path)
    container_raw = load_lexicon_container(path)
    lexicon = LexiconContainer.from_dict(container_raw)
    LOGGER.info('lexicon.load.done entries=%s version=%s', len(lexicon.entries), lexicon.meta.version)
    return lexicon


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_parser()
    args = resolve_args(parser.parse_args(argv))
    settings = load_settings()

    setup_logging(
        app_name='lslm_auto_learning',
        log_dir=args.log_dir,
        console_level=logging.DEBUG if args.debug else logging.INFO,
    )

    lexicon_path = Path(args.lexicon)
    if not lexicon_path.exists():
        raise FileNotFoundError(f'Lexicon file not found: {lexicon_path}')

    lexicon = load_lexicon(lexicon_path)
    normalizer = SurfaceNormalizer(lexicon)
    runtime_config = LearningRuntimeConfig(
        trace_dir=args.trace_dir,
        dataset_dir=args.dataset_dir,
        save_trace=not args.no_trace,
        save_dataset=not args.no_dataset,
        policy_memory_path=args.policy_memory,
        use_policy_memory=not args.no_policy_memory,
        action_bandit_path=args.action_bandit,
        use_action_bandit=not args.no_action_bandit,
        policy_memory_limit=max(1, int(get_setting(settings, 'learning', 'runtime', 'policy_memory_limit', default=4))),
        teacher_target_weight=float(args.teacher_target_weight),
    )
    target_generator = build_target_generator(
        args.target_mode,
        config=build_dataclass_config(LLMTargetGeneratorConfig, get_setting(settings, 'llm', 'target_generation', default={})),
    )
    external_evaluator = build_external_evaluator(
        args.external_mode,
        llm_config=build_dataclass_config(LLMExternalEvaluatorConfig, get_setting(settings, 'llm', 'external_evaluation', default={})),
        heuristic_config=build_dataclass_config(HeuristicExternalEvaluatorConfig, get_setting(settings, 'llm', 'heuristic_external', default={})),
    )
    reward_aggregator = RewardAggregator(
        RewardAggregatorConfig(
            alpha=float(args.alpha),
            beta=float(args.beta),
            fallback_strategy=str(args.external_fallback),
            neutral_external_score=float(args.neutral_external_score),
            use_power_transform=bool(get_setting(settings, 'learning', 'reward_aggregator', 'use_power_transform', default=False)),
            external_power=float(get_setting(settings, 'learning', 'reward_aggregator', 'external_power', default=1.5)),
        )
    )

    if args.input_mode == 'llm':
        input_generator = LLMInputGenerator(
            config=build_dataclass_config(LLMInputGeneratorConfig, get_setting(settings, 'llm', 'input_generation', default={}))
        )
    else:
        input_generator = EchoInputGenerator(args.seed_text)

    policy_memory = None
    action_bandit = None
    if runtime_config.use_policy_memory:
        policy_memory = PolicyMemoryStore(
            runtime_config.policy_memory_path,
            config=build_dataclass_config(PolicyMemoryConfig, get_setting(settings, 'policy_memory', default={})),
            autoload=True,
        )
    if runtime_config.use_action_bandit:
        action_bandit = ActionBanditStore(
            runtime_config.action_bandit_path,
            config=build_dataclass_config(ActionBanditConfig, get_setting(settings, 'learning', 'action_bandit', default={})),
            autoload=True,
        )
    teacher_reranker = TeacherGuidedReranker(
        build_dataclass_config(TeacherGuidanceConfig, get_setting(settings, 'teacher_guidance', default={}))
    )

    session_id = new_session_id('autolearnsess')
    dialogue_state = DialogueState()
    history_inputs: list[str] = []
    history_targets: list[str] = []
    history_responses: list[str] = []

    episode_count = max(1, int(args.episodes))
    report_every = max(1, int(args.report_every))

    LOGGER.info(
        'auto_loop_learning.start session_id=%s episodes=%s input_mode=%s target_mode=%s external_mode=%s',
        session_id,
        episode_count,
        args.input_mode,
        args.target_mode,
        args.external_mode,
    )

    for episode_index in range(1, episode_count + 1):
        generated_input = input_generator.generate(
            loop_index=int(args.loop_index_offset) + episode_index,
            history_inputs=history_inputs,
            history_targets=history_targets,
            seed_topic=args.seed_topic,
        )
        history_inputs.append(generated_input.text)

        result = run_learning_episode(
            raw_text=generated_input.text,
            lexicon=lexicon,
            normalizer=normalizer,
            runtime_config=runtime_config,
            target_generator=target_generator,
            external_evaluator=external_evaluator,
            reward_aggregator=reward_aggregator,
            dialogue_state=dialogue_state,
            session_id=session_id,
            policy_memory=policy_memory,
            teacher_reranker=teacher_reranker,
            action_bandit=action_bandit,
        )
        dialogue_state = result.next_dialogue_state or dialogue_state
        history_targets.append(result.generated_target.text)
        history_responses.append(result.response_text)

        if episode_index % report_every == 0 or episode_index == episode_count:
            print(f'[episode {episode_index}/{episode_count}]')
            print(f'[input] {generated_input.text}')
            print(f'[target] {result.generated_target.text}')
            print(f'[response] {result.response_text}')
            print(
                f'[reward] total={result.trace.reward.total:.4f} '
                f'internal={result.trace.reward.internal.total:.4f} '
                f'external={result.trace.reward.external.total:.4f}'
            )

    LOGGER.info('auto_loop_learning.done session_id=%s episodes=%s', session_id, episode_count)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
